### ISSUE TITLE
Fully automated releases

### ISSUE THREAD

**Issue by mockitoguy** [linkedin/play-parseq#9]
### Problem statement

Let's automate the releases of play-parseq. Goals:
 - releases to Maven Central to streamline consumption by the community (and to create more engaged community)
 - release notes generation
 - example LinkedIn OS project that has full release automation

### Solution options

1. Automate SBT build
2. Migrate to Gradle and automate with Gradle plugins
3. Add Gradle for releases, delegate to SBT

Discussion (with @FranklinYinanDing):
- ad1) SBT is a dead. At LinkedIn we actively migrate to Gradle. SBT automation will duplicate Gradle automation we use in other projects.
- ad2) Migrate to Gradle is ideal but adds extra effort.
- ad3) Good pragmatic approach. We can get the releases automated without committing to full SBT->Gradle migration. We demonstrate how Gradle can wrap foreign build tool to automate releases. Risk exists that Gradle-SBT layer gets complicated and hard to maintain (if that happens we'll do option 2).

### Implementation

I suggest to start using Shipkit Gradle plugins (http://shipkit.org) that Mockito community leverages to implement automated releases.

#### Suggested design
 - Enable Travis CI
 - Use and configure Shipkit Gradle plugins
   - Gradle will delegate to SBT to run build
   - Every PR merged to master will produce a new version in Maven Central
   - Documentation and release notes are automatically generated

#### Milestone 1

Automated releases to JCenter (very visible public repo)

- [x] - SBT integration - #11 - @FranklinYinanDing 
- [x] - enable Travis CI job - #12 - @FranklinYinanDing 
- [x] - request admin rights to the project so that we can inspect / review / update Travis CI configuration.
- [x] - Enable automated releases to Bintray - #10 - @mockitoguy
- [x] - Document how releases work - #19 - @mockitoguy

#### Milestone 2

Automated releases to Maven Central, easy local testing.

- Convenient local testing (easy way to build local snapshot) - @mockitoguy
- Maven Central releases
  - [ ] - request Maven Central releases for "com.linkedIn.play-parseq" libraries - #18
- LinkedIn Artifactory releases (optional)

Thoughts / feedback?

Exciting!!! Let's get the releases fully automated and provide an example for other LinkedIn projects 🗡

**Comment by mockitoguy** [comment]
Hey team! I'm blocked on few things:
 - can you enable Travis CI?
 - can you give me admin rights to the project (see the description why)
Thanks!

**Comment by mockitoguy** [comment]
Update: I updated the description with the plan.

**Comment by FranklinYinanDing** [comment]
I have contacted the open-source team for giving us admin rights, no update yet. Will keep following.

**Comment by mockitoguy** [comment]
Great! I did the same.

Update: we're publishing to a test public repo, see:
- https://bintray.com/linkedin/test-repo/play-parseq/0.8.1#files/com%2Flinkedin%2Fplay-parseq%2Fplay-parseq-trace-scala_2.12%2F0.8.1
- https://dl.bintray.com/linkedin/test-repo/

When we're ready, we'll publish to Maven Central and JCenter.

**Comment by mockitoguy** [comment]
We're in maven central. We can close this. Thanks a lot Yinan for working on all the details!
